---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  eval = T
)
```

# gdistanceR

<!-- badges: start -->
<!-- badges: end -->

The goal of gdistanceR is to interact with the Google Distance MAtrix API.

## Installation

<!--You can install the released version of gdistanceR from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("gdistanceR")
```-->

Install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Shaunson26/gdistanceR")
```
## Example

```{r example}
library(gdistanceR)
```

```{r}
# Return least formatted object from the API call - JSON to list
rs <- get_distances(origins = 'Liverpool 2170',
                    destinations = 'St Leonards 2065')

# Wrangle into a data.frame
wrs <- wrangle_distances(rs)

wrs
```


```{r}
# Return least formatted object from the API call - JSON to list
rs_multi <- get_distances(origins = c('298 Macquarie St Liverpool 2170', 'Campbelltown 2560'),
                    destinations = '1 Reserve Road Leonards 2065')

# Wrangle into a data.frame
wrs_multi <- wrangle_distances(rs_multi)

wrs_multi
```

